apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nl2ml-form
  name: nl2ml-form-db-claim
spec:
  storageClassName: default-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nl2ml-form
  name: nl2ml-form-claim
spec:
  storageClassName: default-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi